* Chronological Journal
*** offset
**** sprinting [2017-01-26 Thu 07:30]

***** initial setup

initial buffer setup
[2017-01-26 Thu 07:31]

set up and formatted script.
[2017-01-26 Thu 07:35]

***** begin movie

****** wakeup scene

******* groggy intros

Kane woke up first.
smokes
man
sarcastic
[2017-01-26 Thu 07:37]

Lambert
young woman
maybe dumb?

Dallas

Ash

Parker and Brett are friends

cat and Ripley are friends

******* cast

Dallas.........Captain
Kane...........Executive Officer
Ripley.........Warrant Officer woman, sarcastic
Ash............Science Officer
Lambert........Navigator woman, whiny
Parker.........Engineer, dominant, abusive towards brett mildly
Brett..........Engineering Technician, submissive
Jones..........Cat

Mother - computer

******* secret comms for dallas; unrecognizable location

mother - eyes only comms for Dallas
[2017-01-26 Thu 07:42]

ripley and cat very good friends
[2017-01-26 Thu 07:42]

out of hypersleep in the wrong system
[2017-01-26 Thu 07:43]

****** mission revealed - distress beacon
******* NOSTROMO

Factory Starship

Function:           Petroleum tanker and Refinery.
Capacity:           2000,000,000 tons.
Length:             One and one half kilometers.
   
******* wrong system

in middle of nowhere, no one around
shouldn't be here.
[2017-01-26 Thu 07:44]

******* dallas: mother diverted us for a distress beacon

from QBR 157, 052

legally obligated to investigate distress beacons

We're contractually obligated under Section B2...

Transmissions received in non-
commercial lanes...

Dallas' call: going in to investigate.

******* Ash is being a little evasive

Dallas: "can we land on it?"
Ash: "the other ship did"

****** planetary approach

cargo dropped off in orbit.
[2017-01-26 Thu 07:51]

nostromo descends.
[2017-01-26 Thu 07:51]

turbulence, thick atmosphere

engineering problems, compressor down, 
hard landing
electrical fire

(very remote possibility: 
Ash didn't hypersleep
he would've had time to sabotage the ship to experience severe malfunctions upon landing stress)

no hull breach.

ripley: 15-20h repair estimate

same transmission every thirty-two seconds.  

making an armed expedition with kane and lambert
[2017-01-26 Thu 07:59]

****** repair bay

little implied sexual harassment from the idiot twins
want shares from salvage.
[2017-01-26 Thu 07:59]

****** expedition

ash oversees while humans go on expedition
little weird, why not send the robot on a dangerous mission?

dallas, ash and Kane going out.

****** Ripley maybe catches ash looking suspicious

does the furtive monitor shutoff when she talks to him

she can't see what was on her screen

******* ash still answering questions evasively:

RIPLEY
Have you tried putting the
transmission through ECIU.
              
ASH
(voice over)
Mother hasn't identified it as yet.
It's not a language.
              
****** alien ship discovered

******* team investigates inside
lost connection
transmission from ship very powerful

transmission was an automatic recording in a derelict ship

tunnel leading below in the rock
kane investigates
warmer there

******* Ripley finds warning; Ash zero empathy

Ripley's study of the transmission yields results before Ash's. Strange:

RIPLEY
Ash, tell Dallas Mother speculates
that the noise is some kind of
warning.

warning can't get through

ash vetoes ripley going to warn dallas, because minimum takeoff crew.

ASH
What's the point.  In the time
it take to get there.  They'll
know if it's a warning.

robot has zero empathy.

******* investigation cont

cave is tropical heat

kane finds egg chamber with thousands of eggs
[2017-01-26 Thu 08:13]

Kane gets facehugger through facemask.
[2017-01-26 Thu 08:43]

******* contact reestablished with expedition

kane is injured, dallas reports

ripley at intercom
ash at inner lock hatch
[2017-01-26 Thu 08:44]

ripley demands details on Kane's condition.
Dallas: organism attached to him.
Ripley: infection risk
Dallas: order open airlock
Ripley: quarantine. refuses

ash overrides hatch with emergency switch
ripley: disbelief that ash overrode her authority as acting ship officer on board

******* medbay

can't remove facehugger without ripping off face
and/or tail around neck

******* ripley unjustly chastised

Dallas: When I give an order, I expect it to be obeyed.
RIPLEY: Even if it's against the law.
DALLAS: That's right.
Dallas alpha.

Lambert steps forward and slaps Ripley across the face.
LAMBERT: You were going to leave us out there.
Lambert emotional bitch.

Ripley lawful, intelligent.

I guess Brett is the submissive but more intelligent one, and Parker is the black aggressive one.

******* medbay

facehugger keeping host alive despite alien biology and radically different atmospheres
AND melted through facemask. insane.

can't tell brett and parker apart.

brett is white subbie
parker aggressive black
got it.

It paralyzes him, puts him into a coma, then keeps him alive.

suggestion: cut it off
Ash warns against
Dallas is for

knicks leg with knife
blood burns through decks

has molecular acid for blood
Wonderful defense mechanism. You don't dare kill it.

They should just perform the surgery outside in a tent on a rock floor.

Ash against trying to remove it again.

growing stain in Kane's chest cavity blocks x-rays.

******* engineering

Parker sexually harasses Ripley
Ripley handles him.

******* ripley questions Ash on status - suspicious rationalizations, low ethics

Ash tetchy answering:

ASH: It's got an outer layer of protein polysaccharides.  A lot of Amino Acids for prolonged reistance to adverse environmental conditions... That enough for you.

Interesting combination of elements making it one tough little son-of-a-bitch...

RIPLEY: Is that why you let it in.

ASH: I was following a direct order. Remember.

RIPLEY: While Dallas and Kane are off the ship, I'm Senior Officer.

ASH: Yes, of course -- I forgot.

RIPLEY: You also forgot the science division's basic quarantine law.

ASH: No.  That I didn't forget.

RIPLEY: You just broke it.

ASH: What would you have done with Kane... His only chance at staying alive was to get into the infirmary.

RIPLEY: By breaking quarantine procedure you risk everybody's life.

ASH: Maybe I should have let him die out there. Maybe I have jeopardized the rest of us...It's a risk I'm willing to take.

RIPLEY: This is your official position as a science officer. Not exactly out of
the manual.

ASH: The first position of science is the protection and betterment of human
life. I take my responsibility as seriously as you do... you do your job and
I'll do mine.

Ripley stands...looks at Ash. Walks out.

[2017-01-26 Thu 09:01]

******* 
**** sprinted [2017-01-26 Thu 09:03]

***** proc'd sprinted. [2017-01-26 Thu 09:59]

***** review notes to orient

****** sort

****** todo plan for confronting Dallas

secret message that Dallas received from Mother

must've been telling him that the distress beacon might have extraterrestrial origin

that's why he brooked no argument about checking it out

and most tellingly, that's why he had the expedition bring weapons along.

Still strange that he brought Lambert instead of Ash on the expedition.

So Dallas knew something in advance.

But it's likely that Mother had another, different message for Ash.

Or maybe Ash knew before the expedition even set out.

But that's a bridge too far for Dallas right now.

To initiate a discussion, just tell him this:

"Your secret message from Mother told you the transmission might be extraterrestrial in origin, didn't it. That's why you had the expedition take weapons."

This puts the blame back on Dallas for Kane's condition, puts him on the psychological defensive. 

Now to defuse that defensiveness:

"I've been watching Ash. I think he Mother had a message for him too - a very different one."

Dallas may object that this is about opening the hatch.

"Forget about the hatch. Do you know what Ash said while you were away?"

Then quote Ash: "What difference does it make. If it's a warning, they'll know before you can get there."

Go through your suspicions: 

"I think Ash wants to study the organism and doesn't care about our lives. 

I think he already knew it was a warning, but withheld that information so that you would go forward without adequate caution.

I think he's the one responsible for Kane's current condition.

How could I, a Warrant Officer, figure out that it was a warning, with Mother's help, before the Science Officer?

I know you do care about our lives. That's why I need you to believe me. We've got an alien that's already incapacitated one of us, and a possible traitor. I am afraid."

[2017-01-26 Thu 11:13]

****** continue sort

******* reasoning through implications of evidence: ship, egg, facehugger

ship's age unknown
could be very old
probably is, considering no contact with alien race all this time

which would mean eggs are also very old

if ship is warning about eggs, then ship and eggs aren't allied

eggs aren't stored in ship. they're stored in a den beneath.

so we've discovered two alien races, not one. and one ate the other. then went into hibernation.

fact: facehugger instantly overcame human suit defenses and adapted to human physiology to such a degree that it kept its first subject alive.

thus either facehuggers are designed for humans, or they are super-advanced

leans towards super-advanced.

we are witnessing the beginning of a parasitical lifecyle, from egg to infection vector.

unknown whether the next phase of the lifecycle will successfully eventuate.
possibly not, given the great age, harsh planetary conditions, and unfamiliar biology

however, possibly so, given amazing capabilities demonstrated so far.
safest to assume next stage of life form will eventuate
and that the end game is another derelict ship
therefore, whole crew is at risk

recommended solution: dump Kane and take off.
alternate solution: deep freeze Kane and take off.

******** todo freeze kane ASAP

******** todo share suspicions on facehugger lifecycle with Dallas

[2017-01-26 Thu 11:42]

******* continue sort
******* likely saboteur: Ash
******* Why would Yutani Corp risk such an expensive ship?

because first contact is worth it

need something isolated, small crew, that unsuspiciously can travel deep space routes

need something they can slip a science officer on board of

and that has an advanced AI

guess they figure they know where it's gonna be, and they can always pick it up later.

perhaps most importantly: 

If they make contact with live aliens, they don't want to give them something nimble, mobile, stealthy and military.

They want to give them a barge.

A refinery probably doesn't give them much they can use.

[2017-01-26 Thu 11:50]
******* done sorting and brainstorming 
[2017-01-26 Thu 11:51]

**** sprinting [2017-01-26 Thu 11:53]

***** proc'd sprinted
[2017-01-26 Thu 12:53]

***** do another deep sort quick pass

done.
[2017-01-26 Thu 12:56]

***** script events continue

****** facehugger found dead; Ash pro-facehugger

facehugger falls off Kane
face covered in sucker marks
suckers would've been easy to remove. just some superficial skin loss to break suction.
[2017-01-26 Thu 13:05]

facehugger now missing somewhere in the ship

decide to try to catch it.

ASH As long as we're careful not to damage it.

^Ash with another fucking pro-facehugger comment, just barely plausibly reasonable, due to molecular blood. But damage is broader than "cut".
[2017-01-26 Thu 13:07]

tube-like mouth

Ash pronounces it dead.

****** Ash puts preservation of specimen above crew safety

weird exchange in which Ripley wants the dangerous biohazard discarded, and Ash makes poorly reasoned responses, and then Dallas bizarrely defers to Ash.

Maybe Mother's instructions to Dallas gave Ash significant authority.

RIPLEY Let's get rid of it.
   
ASH This has to go back. This is our first contact with a specimen like this. All kinds of tests need to be run.

RIPLEY That thing bled acid. God knows what it'll do when it's dead.
   
ASH I think it's safe to assume it's not a zombie... Dallas, we have to keep this specimen.

Pause.

DALLAS You're the science officer. It's your decision.

ASH Then it's made... I'll seal it in a stasis tube.

^This should've been done with Kane immediately.

****** Ash completely unconcerned with Kane, only with specimen

RIPLEY What about Kane.

Ash turns back to the bunk. Studies the life support gauges. Kane continues to breathe steadily.

ASH Running a fever. And still unconscious. The machine will bring his temperature down. His vital functions are strong... who knows, he may make it.

Ash begins to seal the Alien in a large vacuum tube.

Kane is VERY contaminated, with alien mass growing in chest, and these idiots show no thought of operating, or putting into stasis.
[2017-01-26 Thu 13:12]

****** Dallas is neutered alpha - Company has compromised this crew & mission

Ripley confronts Dallas about leaving safety decision to Ash

what follows is a stupid conversation between two stupid, emotional people.

Ripley is clearly flawed - too by the book, too teacher's pet, too emotionally involved in Dallas' alpha leadership, in getting his approval, in a fair shake from him.

And Dallas is ground down to mindless obedience by the Corp. A sad picture of a neutered alpha. I wonder if they have something on him, or he's merely learned how the world works.

Ash has final authority over all things science
by the Company's orders.
It's not SOP
SOP is whatever the Co says.

These are the words of slaves. He's merely an alpha for hire, with no control over his crew composition. Truly neutered. Dystopian future.

Ripley's bookish instincts are bad as well, trying to overcomplete repairs when there's a potential facehugger invasion mustering to wipe them out. Dallas wants liftoff early, and is right.

****** dicey but successful liftoff

deep-space rig not designed for this sort of atmospheric planetary stuf
[2017-01-26 Thu 13:20]

****** commence lightspeed travel

impressive.
[2017-01-26 Thu 13:20]

must be why they needed a big ship
lightspeed probably isn't a common feature.

guess that undermines my hypothesis that they didn't want to give the aliens something fast.

But this ship has a full science bay - that's gotta be a huge consideration.

The only other consideration was probably how to make it plausibly deniable.

the windfall from such a discovery outweigh any other ethical considerations.

Yutani already knows the value of alien tech, according to later franchise canon.

****** Parkett actually has the correct freezing idea, and is mocked

PARKER The best thing to do is just to freeze him. Stop the goddam disease. He can get a doctor to look at him when we get back home.
   
****** Kane wakes up

Ash still evasive about every little thing. Perfect for a deceiver. Never know when he's lying.

KANE Mouth's dry...can I have some water.

Instantly, Ash brings him a plastic cup and water. Kane gulps it down in a swallow.

Strange how Ash is suddenly solicitous of someone's health. Probably because it's the alien's needs, not a human's.
[2017-01-26 Thu 13:25]

Ash very thirsty. Alien drained him of fluids to build its body?

Suffers from near total amnesia. Conveniently adaptive for a parasite. Don't want the host to know he's infected. So he can innocently reintegrate with society.

PARKER Do you hurt.

KANE All over. Feel like somebody's been beating me with a stick for about six years. (smiles) God, I'm hungry.

Sounds like he's been through a rapid unplanned pregnancy.

Everyone about to go into the freezers together, including the facehugger
Absolutely no reason to have delayed Kane's entry into the freezers.

In fact, it showed total disregard for his life.
How could anyone assume that the facehugger's alien biology would've been able to continue to keep him alive?
[2017-01-26 Thu 13:28]

ASH Breathe deeply.
Kane screams.

Lol. Ash is giving him Lamaze tips.

chestburster appears, runs.
[2017-01-26 Thu 13:30]

****** a chorus of idiots realize they're fucked.

PARKER It was growing in him the whole time and he didn't even know it.

ASH It used him for an incubator.

RIPLEY That means we've got another one.

DALLAS Yeah. And it's loose on the ship.

Nobody thought to check the x-rays, apparently.
Except Ash, who wanted it to happen.

****** emergency planning

******* initial

apparently they went looking for it. kinda dumb. what if it was hungry after birth?

RIPLEY We have to catch it and eject it from the ship.

ASH Our supplies are based on us spending a limited amount of time out of suspended animation. Strictly limited.

RIPLEY First we have to find it.

Ash is in favor of not catching it, once again.

Not so sure they'd be in danger in the freezers. Many predators wouldn't recognize a frozen human encased in machinery as prey. Perhaps their lighted glass displays would be sufficient clue. They could always lock the door.

Clearly nobody knows Ash is a robot at this point, or they'd be sending him to catch it.

Stupidly, they hold a funeral before dealing with the alien. Time is critical. This thing clearly moves fast and takes down spacecraft.
[2017-01-26 Thu 13:34]

1 week supply of food and oxygen.

******* Parker's plan - depressurize

problem: insufficient air afterwards.

ASH I hate to point this out but it might be better off without oxygen. It lived that way long enough.

ignores the blowing it out portion

******* problem - lost visual comms on B and C decks

******* dallas' plan - flush it room by room, then trap it

build a net, and a shock prod

****** cynicism, sorrow and sex
******* Dallas confronts Ash (finally)

Ash avoidant
Dallas insistent, dominant

Dallas accuses him of wanting the alien to stay alive. Asks why. We're both working for the same company. Just clue me in.

Ash denies everything, acts offended. 

Ash enraged. Probably doesn't like having to lie.

******* Dallas and Ripley fuck

He's going spacer nuts.
They're finally on the same side, but defeated by the Corp.
Mating is an act of hope against the void.
[2017-01-26 Thu 13:41]
