*** offset

**** ship + egg + facehugger = 2 races, lethal danger

ship's age unknown
could be very old
probably is, considering no contact with alien race all this time

which would mean eggs are also very old

if ship is warning about eggs, then ship and eggs aren't allied

eggs aren't stored in ship. they're stored in a den beneath.

so we've discovered two alien races, not one. and one ate the other. then went into hibernation.

fact: facehugger instantly overcame human suit defenses and adapted to human physiology to such a degree that it kept its first subject alive.

thus either facehuggers are designed for humans, or they are super-advanced

leans towards super-advanced.

we are witnessing the beginning of a parasitical lifecyle, from egg to infection vector.

unknown whether the next phase of the lifecycle will successfully eventuate.
possibly not, given the great age, harsh planetary conditions, and unfamiliar biology

however, possibly so, given amazing capabilities demonstrated so far.
safest to assume next stage of life form will eventuate
and that the end game is another derelict ship
therefore, whole crew is at risk

recommended solution: dump Kane and take off.
alternate solution: deep freeze Kane and take off.
