* 1sprinting.org
file to:
[[file:~/1-mansort/Alien-demo/1-by-time][file:~/1-mansort/Alien-demo/1-by-time]]
[[file:~/1-mansort/Alien-demo/5-scratch][file:~/1-mansort/Alien-demo/5-scratch]]

* sprinting [2017-01-26 Thu 11:53]

** proc'd sprinted
[2017-01-26 Thu 12:53]

** do another deep sort quick pass

done.
[2017-01-26 Thu 12:56]

** script events continue

*** facehugger found dead; Ash pro-facehugger

facehugger falls off Kane
face covered in sucker marks
suckers would've been easy to remove. just some superficial skin loss to break suction.
[2017-01-26 Thu 13:05]

facehugger now missing somewhere in the ship

decide to try to catch it.

ASH As long as we're careful not to damage it.

^Ash with another fucking pro-facehugger comment, just barely plausibly reasonable, due to molecular blood. But damage is broader than "cut".
[2017-01-26 Thu 13:07]

tube-like mouth

Ash pronounces it dead.

*** Ash puts preservation of specimen above crew safety

weird exchange in which Ripley wants the dangerous biohazard discarded, and Ash makes poorly reasoned responses, and then Dallas bizarrely defers to Ash.

Maybe Mother's instructions to Dallas gave Ash significant authority.

RIPLEY Let's get rid of it.
   
ASH This has to go back. This is our first contact with a specimen like this. All kinds of tests need to be run.

RIPLEY That thing bled acid. God knows what it'll do when it's dead.
   
ASH I think it's safe to assume it's not a zombie... Dallas, we have to keep this specimen.

Pause.

DALLAS You're the science officer. It's your decision.

ASH Then it's made... I'll seal it in a stasis tube.

^This should've been done with Kane immediately.

*** Ash completely unconcerned with Kane, only with specimen

RIPLEY What about Kane.

Ash turns back to the bunk. Studies the life support gauges. Kane continues to breathe steadily.

ASH Running a fever. And still unconscious. The machine will bring his temperature down. His vital functions are strong... who knows, he may make it.

Ash begins to seal the Alien in a large vacuum tube.

Kane is VERY contaminated, with alien mass growing in chest, and these idiots show no thought of operating, or putting into stasis.
[2017-01-26 Thu 13:12]

*** Dallas is neutered alpha - Company has compromised this crew & mission

Ripley confronts Dallas about leaving safety decision to Ash

what follows is a stupid conversation between two stupid, emotional people.

Ripley is clearly flawed - too by the book, too teacher's pet, too emotionally involved in Dallas' alpha leadership, in getting his approval, in a fair shake from him.

And Dallas is ground down to mindless obedience by the Corp. A sad picture of a neutered alpha. I wonder if they have something on him, or he's merely learned how the world works.

Ash has final authority over all things science
by the Company's orders.
It's not SOP
SOP is whatever the Co says.

These are the words of slaves. He's merely an alpha for hire, with no control over his crew composition. Truly neutered. Dystopian future.

Ripley's bookish instincts are bad as well, trying to overcomplete repairs when there's a potential facehugger invasion mustering to wipe them out. Dallas wants liftoff early, and is right.

*** dicey but successful liftoff

deep-space rig not designed for this sort of atmospheric planetary stuf
[2017-01-26 Thu 13:20]

*** commence lightspeed travel

impressive.
[2017-01-26 Thu 13:20]

must be why they needed a big ship
lightspeed probably isn't a common feature.

guess that undermines my hypothesis that they didn't want to give the aliens something fast.

But this ship has a full science bay - that's gotta be a huge consideration.

The only other consideration was probably how to make it plausibly deniable.

the windfall from such a discovery outweigh any other ethical considerations.

Yutani already knows the value of alien tech, according to later franchise canon.

*** Parkett actually has the correct freezing idea, and is mocked

PARKER The best thing to do is just to freeze him. Stop the goddam disease. He can get a doctor to look at him when we get back home.
   
*** Kane wakes up

Ash still evasive about every little thing. Perfect for a deceiver. Never know when he's lying.

KANE Mouth's dry...can I have some water.

Instantly, Ash brings him a plastic cup and water. Kane gulps it down in a swallow.

Strange how Ash is suddenly solicitous of someone's health. Probably because it's the alien's needs, not a human's.
[2017-01-26 Thu 13:25]

Ash very thirsty. Alien drained him of fluids to build its body?

Suffers from near total amnesia. Conveniently adaptive for a parasite. Don't want the host to know he's infected. So he can innocently reintegrate with society.

PARKER Do you hurt.

KANE All over. Feel like somebody's been beating me with a stick for about six years. (smiles) God, I'm hungry.

Sounds like he's been through a rapid unplanned pregnancy.

Everyone about to go into the freezers together, including the facehugger
Absolutely no reason to have delayed Kane's entry into the freezers.

In fact, it showed total disregard for his life.
How could anyone assume that the facehugger's alien biology would've been able to continue to keep him alive?
[2017-01-26 Thu 13:28]

ASH Breathe deeply.
Kane screams.

Lol. Ash is giving him Lamaze tips.

chestburster appears, runs.
[2017-01-26 Thu 13:30]

*** a chorus of idiots realize they're fucked.

PARKER It was growing in him the whole time and he didn't even know it.

ASH It used him for an incubator.

RIPLEY That means we've got another one.

DALLAS Yeah. And it's loose on the ship.

Nobody thought to check the x-rays, apparently.
Except Ash, who wanted it to happen.

*** emergency planning

**** initial

apparently they went looking for it. kinda dumb. what if it was hungry after birth?

RIPLEY We have to catch it and eject it from the ship.

ASH Our supplies are based on us spending a limited amount of time out of suspended animation. Strictly limited.

RIPLEY First we have to find it.

Ash is in favor of not catching it, once again.

Not so sure they'd be in danger in the freezers. Many predators wouldn't recognize a frozen human encased in machinery as prey. Perhaps their lighted glass displays would be sufficient clue. They could always lock the door.

Clearly nobody knows Ash is a robot at this point, or they'd be sending him to catch it.

Stupidly, they hold a funeral before dealing with the alien. Time is critical. This thing clearly moves fast and takes down spacecraft.
[2017-01-26 Thu 13:34]

1 week supply of food and oxygen.

**** Parker's plan - depressurize

problem: insufficient air afterwards.

ASH I hate to point this out but it might be better off without oxygen. It lived that way long enough.

ignores the blowing it out portion

**** problem - lost visual comms on B and C decks

**** dallas' plan - flush it room by room, then trap it

build a net, and a shock prod

*** cynicism, sorrow and sex
**** Dallas confronts Ash (finally)

Ash avoidant
Dallas insistent, dominant

Dallas accuses him of wanting the alien to stay alive. Asks why. We're both working for the same company. Just clue me in.

Ash denies everything, acts offended. 

Ash enraged. Probably doesn't like having to lie.

**** Dallas and Ripley fuck

He's going spacer nuts.
They're finally on the same side, but defeated by the Corp.
Mating is an act of hope against the void.
[2017-01-26 Thu 13:41]

** Todo

resume script
