* 1sprinting.org
file to:
[[file:~/1-mansort/Alien-demo/1-by-time][file:~/1-mansort/Alien-demo/1-by-time]]
[[file:~/1-mansort/Alien-demo/5-scratch][file:~/1-mansort/Alien-demo/5-scratch]]

* sprinting [2017-01-26 Thu 13:43]

** proc sprinted

Clearly Mother and the Corp are implicated at this point

This mission is Crew Expendable.

Ash is a psychopathic suicidal traitor.

done proc
[2017-01-26 Thu 14:02]

** do deep sorting pass, to find next actions

*** todo mitigate Mother's power to betray

Mother is a traitor.
She doesn't want the alien to lose, possibly.
So the alien may receive aid and comfort in the form of doors opening, foiling of human hunting plans, etc.
Is there a way to disable mother?

do their planning away from her eyes

disable rest of her sensors

possibly attempt to negotiate a survival settlement through strike threat

*** hunting strategies

secure zones - block off vent access etc

armed patrols

food traps

use standard weapons, and have sprayable base solution to neutralize blood.

hunt it on the inner decks and cede the outer ones

or bulkhead seal the ship into sections and hunt that way, so a depressurization event doesn't blow all the oxygen.

hull breaches would likely be small and survivable for short periods.

use blunt trauma weapons, e.g. beanbag shotgun, deadfalls, etc.

electrocution traps cauterize, probably

*** siege strategy

they've only got a week

it's got 10 months

spend the week fortifying the hibernation chamber

trust Yutani troops to deal with the alien. Mother will call the cavalry.

Go to sleep. Tell Mother to wake them if the alien starts to penetrate defenses.

Hope that the alien must hibernate without food or water

And that it can be taken out with ease once weakened.

Keep their weapons in the hibernation chamber.

Maybe wake up in staggered shifts occasionally just to keep an eye on developments.

supplies are sufficient for... 7x6 = 42 man days
10x30 = 300 days to destination
If broadcast emergency signal, can maybe reduce that.

could they synth oxygen for one person?
*** hybrid hunting-siege strategy

Ash and Lambert go to sleep immediately

The rest fortify for seige while watching developments and making patrols and building weapons and traps.

Last one in hibernation is Dallas.

** post video thoughts

My suspicions of Mother were overblown
She's nowhere near sentient, unlike Ash.

Her level of betrayal is limited to permissions and preprogrammed instructions.

The command keycard gives almost complete access, except for those instructions reserved for Science eyes only.

Mother wasn't opening hatches - Ash was.
** Todo

proc sprinted
figure out next steps
