* Scratch Inbox

*** offset

*** sprinting [2017-01-26 Thu 07:30]

**** initial setup

initial buffer setup
[2017-01-26 Thu 07:31]

set up and formatted script.
[2017-01-26 Thu 07:35]

**** begin movie

***** wakeup scene

****** groggy intros

Kane woke up first.
smokes
man
sarcastic
[2017-01-26 Thu 07:37]

Lambert
young woman
maybe dumb?

Dallas

Ash

Parker and Brett are friends

cat and Ripley are friends

****** cast

Dallas.........Captain
Kane...........Executive Officer
Ripley.........Warrant Officer woman, sarcastic
Ash............Science Officer
Lambert........Navigator woman, whiny
Parker.........Engineer, dominant, abusive towards brett mildly
Brett..........Engineering Technician, submissive
Jones..........Cat

Mother - computer

****** secret comms for dallas; unrecognizable location

mother - eyes only comms for Dallas
[2017-01-26 Thu 07:42]

ripley and cat very good friends
[2017-01-26 Thu 07:42]

out of hypersleep in the wrong system
[2017-01-26 Thu 07:43]

***** mission revealed - distress beacon
****** NOSTROMO

Factory Starship

Function:           Petroleum tanker and Refinery.
Capacity:           2000,000,000 tons.
Length:             One and one half kilometers.
   
****** wrong system

in middle of nowhere, no one around
shouldn't be here.
[2017-01-26 Thu 07:44]

****** dallas: mother diverted us for a distress beacon

from QBR 157, 052

legally obligated to investigate distress beacons

We're contractually obligated under Section B2...

Transmissions received in non-
commercial lanes...

Dallas' call: going in to investigate.

****** Ash is being a little evasive

Dallas: "can we land on it?"
Ash: "the other ship did"

***** planetary approach

cargo dropped off in orbit.
[2017-01-26 Thu 07:51]

nostromo descends.
[2017-01-26 Thu 07:51]

turbulence, thick atmosphere

engineering problems, compressor down, 
hard landing
electrical fire

(very remote possibility: 
Ash didn't hypersleep
he would've had time to sabotage the ship to experience severe malfunctions upon landing stress)

no hull breach.

ripley: 15-20h repair estimate

same transmission every thirty-two seconds.  

making an armed expedition with kane and lambert
[2017-01-26 Thu 07:59]

***** repair bay

little implied sexual harassment from the idiot twins
want shares from salvage.
[2017-01-26 Thu 07:59]

***** expedition

ash oversees while humans go on expedition
little weird, why not send the robot on a dangerous mission?

dallas, ash and Kane going out.

***** Ripley maybe catches ash looking suspicious

does the furtive monitor shutoff when she talks to him

she can't see what was on her screen

****** ash still answering questions evasively:

RIPLEY
Have you tried putting the
transmission through ECIU.
              
ASH
(voice over)
Mother hasn't identified it as yet.
It's not a language.
              
***** alien ship discovered

****** team investigates inside
lost connection
transmission from ship very powerful

transmission was an automatic recording in a derelict ship

tunnel leading below in the rock
kane investigates
warmer there

****** Ripley finds warning; Ash zero empathy

Ripley's study of the transmission yields results before Ash's. Strange:

RIPLEY
Ash, tell Dallas Mother speculates
that the noise is some kind of
warning.

warning can't get through

ash vetoes ripley going to warn dallas, because minimum takeoff crew.

ASH
What's the point.  In the time
it take to get there.  They'll
know if it's a warning.

robot has zero empathy.

****** investigation cont

cave is tropical heat

kane finds egg chamber with thousands of eggs
[2017-01-26 Thu 08:13]

Kane gets facehugger through facemask.
[2017-01-26 Thu 08:43]

****** contact reestablished with expedition

kane is injured, dallas reports

ripley at intercom
ash at inner lock hatch
[2017-01-26 Thu 08:44]

ripley demands details on Kane's condition.
Dallas: organism attached to him.
Ripley: infection risk
Dallas: order open airlock
Ripley: quarantine. refuses

ash overrides hatch with emergency switch
ripley: disbelief that ash overrode her authority as acting ship officer on board

****** medbay

can't remove facehugger without ripping off face
and/or tail around neck

****** ripley unjustly chastised

Dallas: When I give an order, I expect it to be obeyed.
RIPLEY: Even if it's against the law.
DALLAS: That's right.
Dallas alpha.

Lambert steps forward and slaps Ripley across the face.
LAMBERT: You were going to leave us out there.
Lambert emotional bitch.

Ripley lawful, intelligent.

I guess Brett is the submissive but more intelligent one, and Parker is the black aggressive one.

****** medbay

facehugger keeping host alive despite alien biology and radically different atmospheres
AND melted through facemask. insane.

can't tell brett and parker apart.

brett is white subbie
parker aggressive black
got it.

It paralyzes him, puts him into a coma, then keeps him alive.

suggestion: cut it off
Ash warns against
Dallas is for

knicks leg with knife
blood burns through decks

has molecular acid for blood
Wonderful defense mechanism. You don't dare kill it.

They should just perform the surgery outside in a tent on a rock floor.

Ash against trying to remove it again.

growing stain in Kane's chest cavity blocks x-rays.

****** engineering

Parker sexually harasses Ripley
Ripley handles him.

****** ripley questions Ash on status - suspicious rationalizations, low ethics

Ash tetchy answering:

ASH: It's got an outer layer of protein polysaccharides.  A lot of Amino Acids for prolonged reistance to adverse environmental conditions... That enough for you.

Interesting combination of elements making it one tough little son-of-a-bitch...

RIPLEY: Is that why you let it in.

ASH: I was following a direct order. Remember.

RIPLEY: While Dallas and Kane are off the ship, I'm Senior Officer.

ASH: Yes, of course -- I forgot.

RIPLEY: You also forgot the science division's basic quarantine law.

ASH: No.  That I didn't forget.

RIPLEY: You just broke it.

ASH: What would you have done with Kane... His only chance at staying alive was to get into the infirmary.

RIPLEY: By breaking quarantine procedure you risk everybody's life.

ASH: Maybe I should have let him die out there. Maybe I have jeopardized the rest of us...It's a risk I'm willing to take.

RIPLEY: This is your official position as a science officer. Not exactly out of
the manual.

ASH: The first position of science is the protection and betterment of human
life. I take my responsibility as seriously as you do... you do your job and
I'll do mine.

Ripley stands...looks at Ash. Walks out.

[2017-01-26 Thu 09:01]


