*** offset

**** ash consistently against removing facehugger

**** facehugger found dead; Ash only cares about not damaging it

facehugger falls off Kane
face covered in sucker marks
suckers would've been easy to remove. just some superficial skin loss to break suction.
[2017-01-26 Thu 13:05]

facehugger now missing somewhere in the ship

decide to try to catch it.

ASH As long as we're careful not to damage it.

^Ash with another fucking pro-facehugger comment, just barely plausibly reasonable, due to molecular blood. But damage is broader than "cut".
[2017-01-26 Thu 13:07]

tube-like mouth

Ash pronounces it dead.

**** Ash puts preservation of specimen above crew safety

weird exchange in which Ripley wants the dangerous biohazard discarded, and Ash makes poorly reasoned responses, and then Dallas bizarrely defers to Ash.

Maybe Mother's instructions to Dallas gave Ash significant authority.

RIPLEY Let's get rid of it.
   
ASH This has to go back. This is our first contact with a specimen like this. All kinds of tests need to be run.

RIPLEY That thing bled acid. God knows what it'll do when it's dead.
   
ASH I think it's safe to assume it's not a zombie... Dallas, we have to keep this specimen.

Pause.

DALLAS You're the science officer. It's your decision.

ASH Then it's made... I'll seal it in a stasis tube.

^This should've been done with Kane immediately.

**** Ash still pro-alien, after Kane's death
