*** offset

**** Dallas unjustly chastises ripley - alpha shepherd

Dallas: When I give an order, I expect it to be obeyed.
RIPLEY: Even if it's against the law.
DALLAS: That's right.
Dallas alpha.

**** Dallas is neutered alpha - Company has compromised this crew & mission

Ripley confronts Dallas about leaving safety decision to Ash

what follows is a stupid conversation between two stupid, emotional people.

Ripley is clearly flawed - too by the book, too teacher's pet, too emotionally involved in Dallas' alpha leadership, in getting his approval, in a fair shake from him.

And Dallas is ground down to mindless obedience by the Corp. A sad picture of a neutered alpha. I wonder if they have something on him, or he's merely learned how the world works.

Ash has final authority over all things science
by the Company's orders.
It's not SOP
SOP is whatever the Co says.

These are the words of slaves. He's merely an alpha for hire, with no control over his crew composition. Truly neutered. Dystopian future.

Ripley's bookish instincts are bad as well, trying to overcomplete repairs when there's a potential facehugger invasion mustering to wipe them out. Dallas wants liftoff early, and is right.
