*** offset

**** ripley questions Ash on status - suspicious rationalizations, low ethics

Ash tetchy answering:

ASH: It's got an outer layer of protein polysaccharides.  A lot of Amino Acids for prolonged reistance to adverse environmental conditions... That enough for you.

Interesting combination of elements making it one tough little son-of-a-bitch...

RIPLEY: Is that why you let it in.

ASH: I was following a direct order. Remember.

RIPLEY: While Dallas and Kane are off the ship, I'm Senior Officer.

ASH: Yes, of course -- I forgot.

RIPLEY: You also forgot the science division's basic quarantine law.

ASH: No.  That I didn't forget.

RIPLEY: You just broke it.

ASH: What would you have done with Kane... His only chance at staying alive was to get into the infirmary.

RIPLEY: By breaking quarantine procedure you risk everybody's life.

ASH: Maybe I should have let him die out there. Maybe I have jeopardized the rest of us...It's a risk I'm willing to take.

RIPLEY: This is your official position as a science officer. Not exactly out of
the manual.

ASH: The first position of science is the protection and betterment of human
life. I take my responsibility as seriously as you do... you do your job and
I'll do mine.

Ripley stands...looks at Ash. Walks out.

[2017-01-26 Thu 09:01]
