*** offset

**** TODO They should just perform the surgery outside in a tent on a rock floor.

**** TODO red-pill Dallas

***** Dallas's secret message from Mother: beacon possibly alien

secret message that Dallas received from Mother

must've been telling him that the distress beacon might have extraterrestrial origin

that's why he brooked no argument about checking it out

and most tellingly, that's why he had the expedition bring weapons along.

Still strange that he brought Lambert instead of Ash on the expedition.

So Dallas knew something in advance.

***** Ash secret agenda - study alien

But it's likely that Mother had another, different message for Ash.

Or maybe Ash knew before the expedition even set out.

But that's a bridge too far for Dallas right now.

***** what to tell Dallas

To initiate a discussion, just tell him this:

"Your secret message from Mother told you the transmission might be extraterrestrial in origin, didn't it. That's why you had the expedition take weapons."

This puts the blame back on Dallas for Kane's condition, puts him on the psychological defensive. 

Now to defuse that defensiveness:

"I've been watching Ash. I think he Mother had a message for him too - a very different one."

Dallas may object that this is about opening the hatch.

"Forget about the hatch. Do you know what Ash said while you were away?"

Then quote Ash: "What difference does it make. If it's a warning, they'll know before you can get there."

Go through your suspicions: 

"I think Ash wants to study the organism and doesn't care about our lives. 

I think he already knew it was a warning, but withheld that information so that you would go forward without adequate caution.

I think he's the one responsible for Kane's current condition.

How could I, a Warrant Officer, figure out that it was a warning, with Mother's help, before the Science Officer?

I know you do care about our lives. That's why I need you to believe me. We've got an alien that's already incapacitated one of us, and a possible traitor. I am afraid."

add stuff about alien likely being able to take out ships.

[2017-01-26 Thu 11:13]

**** TODO freeze kane ASAP

**** TODO maroon or murder Ash

he deserves to be murdered

he could be force hibernated instead

but Mother is on his side. She would wake him.

So eject him from a life-pod with stasis instead.

Marooned. Yarr!
